package:
  name: bw_default_backend-dev
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - stats_arrays
    - wrapt
    - brightway_projects-dev
    - bw_processing-dev

test:
  imports:
    - bw_default_backend

about:
  home: "https://github.com/brightway-lca/bw_default_backend"
  license: BSD License
  summary: 'Default backend for brightway using SQLite3 and peewee'
license_family: BSD
